### ISSUE TITLE
Question: Shutdown app

### ISSUE THREAD

**Issue by ghost** [furmada/PythonOS#11]
https://github.com/furmada/PythonOS/blob/master/apps/shutdown/__init__.py

Hi, is this code actually shutdown the host system too? It says sudo `system shutdown`, and I think it's a yes. Can I ask, if pyos were installed in Pi, what it will do? Is this linux/OSX specific code?

I thought this app only shutdown the pyos, and not the host system.

**Comment by furmada** [comment]
The Shutdown app will actually shut down any Linux host system (including the Pi). I made it to prevent users from "pulling the plug" and potentially ruining files. To simply exit Python OS, use the "Quit" app.

And yes, the Linux code to shut down is `sudo shutdown -h now`

**Comment by ghost** [comment]
Ah, I see. I'm a bit confused at first, because I'm not familiar with Pi, and don't know if some commands are same like on Linux.

**Comment by furmada** [comment]
The Pi actually runs Debian Linux, so most (if not all) of the commands you use on Ubuntu work on a Pi as well. 

However, you can install a multitude of other operating systems on the Pi as well. You can see just a few at https://www.raspberrypi.org/downloads/

**Comment by ghost** [comment]
I see. Thanks. Now I feel comfort to play with Python OS and interact with the shell and the API.

**Comment by furmada** [comment]
Awesome. I'm currently working on API docs, so if you have any questions feel free to open another issue.

**Comment by ghost** [comment]
I'm currently tinkering with the api through the apps/ codes. The system to build apps for it is amazingly easy and fun.

**Comment by furmada** [comment]
Thank you. My intention was to make it easy to get started, but powerful enough to handle complex apps (much like Python itself!)

**Comment by ghost** [comment]
I'm honestly think this project should deserve more contributors, because I see a big potential on this. And maybe who knows, Python language itself can integrate to build kernels, and in that time, PythonOS can take advantage on that situation.

**Comment by ghost** [comment]
and, also another question:

Why there is 3 separate applications that serves related function (sleep, quit, shutdown). Why these 3 are not into one application?

**Comment by furmada** [comment]
You're right, the Shutdown and Quit apps could be integrated. The Sleep app is intended to have one-button functionality, so it will probably remain a dedicated app.

**Comment by ghost** [comment]
It will be nice to integrate them both together. As long, the buttons are not too small.

**Comment by furmada** [comment]
I was thinking that I might integrate the apps while dumping the dialog based interface. That way, I could make three big buttons and be able to handle Sleep as well.

**Comment by ghost** [comment]
Nice
