### ISSUE TITLE
Automated unit test for python os on github

### ISSUE THREAD

**Issue by ghost** [furmada/PythonOS#12]
Hey @furmada , did you ever tried travis.ci for automatic test for this repo? It seems gonna save a lot of time finding Python specific bugs with the testings. You also can customize the testing to suit this project, and maybe set a test rules for any other contributors in the future for this project.

Thanks.

**Comment by furmada** [comment]
I have heard of it, but haven't tried it yet. I will look into it for the next release.

**Comment by ghost** [comment]
Nice :smile: 

Maybe I can help with the travis.ci custom test for this project. Overtime, I'll send a pull request to update the travis lint (if used) for this project.

Thanks.

**Comment by furmada** [comment]
If you want to help set up tests, I could add you as a contributor when I start work on a new version (which I'll do when I finish the docs).

**Comment by ghost** [comment]
I will not promise that I can really help, but I can try. Travis tools are somewhat fun to explore and useful to have.

**Comment by ghost** [comment]
Oh, I just realized there's another good alternative called CircleCI. I can debug the code through it on the fly, and running linux commands, while builds is automated. Since this PythonOS is GUI based, CircleCI might be better for this task, cause it will need user input(mouse events, clicks).

**Comment by ghost** [comment]
Oh I forgot. These integrated automated testing doesn't support GUI. So, it's pretty much useless for this project, unless you wanted to build non-gui codes like docker, java spring, rails and stuff.

**Comment by skelic** [comment]
and I was wrong about a thing. I forgot the testing capabilities of the code itself. Means, I can just test the python code if there any part of it make the interpreter return 1.

Example on my packdeb project - https://circleci.com/gh/skelic/packdeb/15

**Comment by furmada** [comment]
That's alright. It may still be useful if I decide to make a backend of some sort (such as an app server or something).
