### ISSUE TITLE
PMan won't update

### ISSUE THREAD

**Issue by ghost** [furmada/PythonOS#21]
doesn't work on any of the following systems I tried (Python OS latest):
- Windows XP Dell Dimension 3100c
- Linux Mint 18 Cinnamon
- Windows 8.1
- Windows 10

good job on the project btw.

**Comment by ghost** [comment]
Do you have Pygame installed?

This version [PythonOS 6 v1.0.1](https://github.com/furmada/PythonOS/releases/tag/v1.01) is running on Python 2 with Pygame.

**Comment by furmada** [comment]
This is a known bug in the development version of Python OS.
Please try the stable version, and comment if the bug still exists there.
The latest stable release is 1.01, available [here](https://github.com/furmada/PythonOS/releases/tag/v1.01)

**Comment by furmada** [comment]
The bug has been fixed as of 1.2 beta1 (pman 2.4)
