### ISSUE TITLE
Review icons

### ISSUE THREAD

**Issue by linusg** [furmada/PythonOS#23]
The Android-like app launcher is very nice, however, the icons don't look as beautiful as they could (sorry @furmada , but are they drawn with MS Paint?). I think of the following:

- Consistent shape is already present and very good, currently rectangular. We should keep that.
- Very important: remove the pixelized borders of objects in the icons.
- Maybe be inspired by Material Design?
- Complete redesign of _About_, _Quit_ and _Sleep_
- _Clock_ is fine, however, _Stopwatch_ and _Timer_ are not unique enough
- As already said, creating a new, smooth version of each icon would be cool, maybe even as `svg` and then exported to `png`.

I would really love to make UI more beautiful. If this is currently not very important on your TODO list, we could keep this for the future.

**Comment by furmada** [comment]
I agree that many of the icons could use a redesign, and I agree that a more beautiful UI is a good thing. However, I am not a graphic artist, and many of the icons in place were done quite quickly, and never intended to be permanent.

Updating the icons is definitely on my TODO list, but fixing bugs in the code is of a higher priority at the moment.
