### ISSUE TITLE
User-specific path in gallery.ds

### ISSUE THREAD

**Issue by linusg** [furmada/PythonOS#24]
Sorry for opening so much issues, but I just found, that in the file `res/gallery.ds` you have this:
```
{"dsApp": "gallery", "path": "C:/Users/Adam/Documents/eclipsepy/pyos6/res/icons"}
```
Is this just fine or will it break things?

**Comment by furmada** [comment]
Thanks for catching this. It was left behind from testing. I have eliminated it and updated .gitignore so that .ds files are not uploaded. They are used as persistent datastores for apps and can be safely removed with no other consequence than loss of data for a specific app.
