### ISSUE TITLE
Quick start problem

### ISSUE THREAD

**Issue by ghost** [furmada/PythonOS#3]
Hi, I tried the following quick start tutorial in the README.md. After creating the app.json and __init__.py with its content, I don't know where to go from there. 

> Now, enter the About app and long press the "Start State Shell" button to launch the Debug App Bind feature. Open your app's folder, then press the green dot button to select it and associate the app with the system. 

I don't know how to go to the 'Start State Shell' and even install 'pyos' properly on my system. Mine is not raspberry. I'm running Ubuntu 16.04. (32 bit)

I tried running pyos.py in the root of directory, and run fine, but it's just print on the window screen, and nothing else. This is what I see - 
![tsjtr5p](https://cloud.githubusercontent.com/assets/20332639/16658082/934cfa70-4497-11e6-9f08-81b2b8539adf.png)

How to actually use this program? Going to wiki only shows you the API documentation.

Thanks for your advance.

**Comment by furmada** [comment]
You are doing everything properly, the bug was caused by PyOS thinking it was running on a Pi. I pushed a new version that should fix this bug.

**Comment by ghost** [comment]
Alright. Let me test the new version and will report if anything else happened.

**Comment by ghost** [comment]
Erm. Hey, is there a way to enable cursor just for debugging/dev/testing? I'm not on touchscreen pc, so it's a bit problem to see where I click, although stuff is functioning. Now, I'm gonna try to click the 'Start Shell'

**Comment by ghost** [comment]
I can open the following state shell smoothly, however a bit hard for a non touchscreen pc.

The problem is I don't really know where my cursor pointing at, and I fail at clicking the 'dot green button' because I just don't see my cursor.

**Comment by furmada** [comment]
I'm sorry for the problems. I did not try the code on a Linux PC other than the Pi, so I did not realize this would happen. The reason your previous issue and this one occurred is because PyOS thinks it is running on the Pi. When I get to my computer I will change the code to enable the cursor on Linux.

**Comment by ghost** [comment]
The previous issue is fixed. Well done. just this new issue (I think just for me at least, because my PC is old and non touchscreen), make things a little steep, but maybe blind clicking will make things run. I currently stuck at dot green button clicking part (can't see :stuck_out_tongue_closed_eyes: ), but others are fine and functional, well I did not hit the part after clicking the green button yet.

Thanks. I think I'll close this issue for now, and maybe you or me will re-open this whenever cursor is added.

**Comment by furmada** [comment]
The newest version should add the cursor on Linux.

**Comment by ghost** [comment]
Hi, the new push is a great feature for me! Now I can navigate easily. Now I encounter a new problem -

After creating the helloworld stuff based on tutorial, and navigated to helloworld dir and clicked green dot button, it spits out this error - 
![screenshot_2016-07-08_11-49-52](https://cloud.githubusercontent.com/assets/20332639/16676922/8c55c862-4502-11e6-8e0f-d537e1edc59a.png)

This is last_error in my temp/ - 
[last_error.txt](https://github.com/furmada/PythonOS/files/353480/last_error.txt)

**Comment by furmada** [comment]
There was a comma after `"onStart"` in the test JSON that snuck in from somewhere (some app.json files have more properties), and that was getting caught by the JSON decoder:

```
...
ValueError: Expecting property name: line 8 column 5 (char 149)
```

**Comment by ghost** [comment]
:smile: 

Things working, and the program (helloworld) appeared in the HOME screen! Nice!
here's my screen shot - 
![pp](https://cloud.githubusercontent.com/assets/20332639/16683899/a4d53e4a-4534-11e6-8f40-be15f3ef44c4.png)

:+1: 

Now I can officially close this issue. Thanks for helping out.

**Comment by furmada** [comment]
You are very welcome. Thank you for helping me iron out problems in the tutorial.

**Comment by ghost** [comment]
You are welcome, too!
